title: 'Tom Chester Music'
default_lang: en
author:
  name: Tom
  email: donnellebt@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'TCMTheme is a custom Grav theme based on the Woo skeleton.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: your-email@domain.com
description: 'Tom Chester Music - musician, conductor, educator, composer'
social:
  -
    url: 'https://www.facebook.com/TomChesterMusic/'
    icon: facebook
  -
    url: 'https://www.instagram.com/chestert13/?hl=en'
    icon: instagram
menu:
  -
    text: About
    link: '#about'
  -
    text: Teaching
    link: '#teaching'
  -
    text: Conducting
    link: '#conducting'
  -
    text: Orchestrating
    link: '#orchestrating'
  -
    text: Testimonials
    link: '#testimonials'

footer:
  text: 'Tom Chester Music provides quality musical support in the Auckland area, combining a wealth of knowledge with an unrelenting passion for making music.'
  address:
    title: 'COME VISIT'
    lines:
      -
        line: '13 Birdwood Avenue'
      -
        line: 'Papatoetoe'
      -
        line: 'Auckland 2025'
  social_title: Socialise
  contact:
    title: 'CONTACT'
    lines:
      -
        text: 021 108 5939
        url: '#'
      -
        text: tom@tomchestermusic.nz
        url: 'tom@tomchestermusic.nz'
